"""Convert pret/pokered music (.asm note data) into an event table for src/game/audio/chip.ts.

Run with `python -I scripts/convert_pokered_music.py`. The source lives in the private
reference library (reference/native-sources/pokered/titlescreen.asm, URL in sources.json).

Engine facts used (pret/pokered audio/engine_1.asm, macros/scripts/audio.asm):
  - `octave N` stores 8 - N; CalculateFrequency shifts the pitch table N - 1 times, so
    pulse-channel C_ in octave N is scientific C(N+1). The wave channel sounds an octave lower.
  - A note lasts length * speed * tempo / 256 frames (the fractional part carries over),
    at the DMG frame rate of 59.7275 Hz.
  - `sound_loop 0, label` loops forever; `sound_loop n, label` plays the block n times.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'reference/native-sources/pokered/titlescreen.asm'
OUT = ROOT / 'src/game/audio/pokered-title.ts'
NOTES = {'C_': 0, 'C#': 1, 'D_': 2, 'D#': 3, 'E_': 4, 'F_': 5, 'F#': 6, 'G_': 7, 'G#': 8, 'A_': 9, 'A#': 10, 'B_': 11}
DRUM = {1: 's', 2: 's', 3: 's', 4: 's', 5: 's', 6: 'k', 7: 'k', 8: 's', 9: 's', 10: 's', 11: 's', 12: 'h', 13: 'h', 14: 'h', 15: 's', 16: 'k', 17: 's', 18: 's', 19: 's'}


def parse(path):
    """Returns {channel label: [(cmd, args)]} plus local labels as ('label', name)."""
    channels, current = {}, None
    for raw in path.read_text().splitlines():
        line = raw.split(';')[0].rstrip()
        if not line.strip(): continue
        m = re.match(r'^(Music_\w+)::', line)
        if m: current = m.group(1); channels[current] = []; continue
        m = re.match(r'^(\.\w+):', line)
        if m: channels[current].append(('label', [m.group(1)])); continue
        parts = line.strip().split(None, 1)
        args = [a.strip() for a in parts[1].split(',')] if len(parts) > 1 else []
        channels[current].append((parts[0], args))
    return channels


def run(code, wave=False, noise=False, max_events=4000, tempo=256):
    labels = {a[0]: i for i, (c, a) in enumerate(code) if c == 'label'}
    # The tempo is global to the music engine; channel 1 sets it for everyone.
    state = dict(speed=12, volume=12, fade=0, octave=4, duty=2, tempo=tempo, drum_speed=12)
    events, loop_at, stack, loops, pc, frac = [], None, [], {}, 0, 0.0
    while pc < len(code) and len(events) < max_events:
        cmd, args = code[pc]; pc += 1
        if cmd == 'tempo': state['tempo'] = int(args[0])
        elif cmd == 'note_type':
            state['speed'] = int(args[0]); state['volume'] = int(args[1]); state['fade'] = int(args[2])
        elif cmd == 'drum_speed': state['drum_speed'] = int(args[0])
        elif cmd == 'octave': state['octave'] = int(args[0])
        elif cmd == 'duty_cycle': state['duty'] = int(args[0])
        elif cmd in ('note', 'rest', 'drum_note'):
            length = int(args[-1])
            speed = state['drum_speed'] if cmd == 'drum_note' else state['speed']
            exact = length * speed * state['tempo'] / 256 + frac
            frames = int(exact); frac = exact - frames
            if cmd == 'rest': pitch = -1
            elif cmd == 'drum_note': pitch = -100 - int(args[0])
            else: pitch = 12 * (state['octave'] + 1) + NOTES[args[0]] + 12 - (12 if wave else 0)
            vol = state['volume'] if not wave else {0: 0, 1: 15, 2: 8, 3: 4}.get(state['volume'], 8)
            events.append([pitch, frames, vol, state['fade'], state['duty']])
        elif cmd == 'sound_call': stack.append(pc); pc = labels[args[0]]
        elif cmd == 'sound_ret': pc = stack.pop()
        elif cmd == 'sound_loop':
            count, target = int(args[0]), args[1]
            if count == 0:
                loop_at = marks.get(target, 0)
                break
            done = loops.get(pc, 0) + 1
            if done < count: loops[pc] = done; pc = labels[target]
            else: loops.pop(pc, None)
        elif cmd == 'label':
            marks[args[0]] = len(events)
        # volume, vibrato, pitch_slide and panning are not modelled.
    return events, loop_at, state['tempo']


marks = {}
channels = parse(SRC)
out = []
tempo = 256
for name, code in channels.items():
    marks = {}
    wave, noise = name.endswith('Ch3'), name.endswith('Ch4')
    events, loop_at, tempo = run(code, wave, noise, tempo=tempo)
    tempo_frames = sum(e[1] for e in events)
    voice = 'noise' if noise else 'triangle' if wave else 'pulse'
    out.append({'name': name, 'voice': voice, 'loopAt': loop_at or 0, 'events': [x for e in events for x in e]})
    print(f'{name}: {len(events)} events, {tempo_frames / 59.7275:.2f}s, loop at event {loop_at}', file=sys.stderr)
lengths = [sum(c['events'][i + 1] for i in range(c['loopAt'] * 5, len(c['events']), 5)) for c in out]
print('loop lengths (frames):', lengths, file=sys.stderr)
OUT.write_text(
    '// Generated by scripts/convert_pokered_music.py from pret/pokered audio/music/titlescreen.asm.\n'
    '// Pokémon Red/Blue opening theme © Nintendo / Creatures / GAME FREAK (route A, PLAN.md §12).\n'
    '// Events are flat [midiOrRest, frames, volume 0-15, fade, duty] tuples; -1 = rest, <= -100 = drum (-100 - instrument).\n'
    f'export const pokeredTitle = {json.dumps(out, separators=(",", ":"))} as const;\n'
    f'export const drumKinds: Record<number, "k" | "s" | "h"> = {json.dumps(DRUM)};\n'
)
